# Generated by Django 4.1.7 on 2023-03-24 00:23

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('administrating', '0002_page_pagetomenu_page_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template_path',
            field=models.FileField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('D:/Projects/UpTrader/uptrader/menu/templates/menu')),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
