# Generated by Django 4.1.7 on 2023-03-24 00:37

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('administrating', '0003_page_template_path_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='template_path',
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('D:/Projects/UpTrader/uptrader/static/templates')),
        ),
    ]
