# Generated by Django 4.1.7 on 2023-03-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrating', '0004_remove_page_template_path_page_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menus',
        ),
        migrations.DeleteModel(
            name='PageToMenu',
        ),
    ]
