# Generated by Django 4.1.7 on 2023-03-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrating', '0005_remove_page_menus_delete_pagetomenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
