# Generated by Django 4.1.7 on 2023-03-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('order', models.SmallIntegerField(default=0)),
                ('menu_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='menu.menu')),
                ('menu_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='menu.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='elements',
            field=models.ManyToManyField(to='menu.menuelement'),
        ),
    ]
