# Generated by Django 4.1.7 on 2023-03-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuelement',
            name='menu_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='menu.menu'),
        ),
    ]
